### PR TITLE
set VCS root field

### PR DESCRIPTION
**Pull request by deadly11ama**
Set a VCS root field, as described in

  https://confluence.jetbrains.com/display/TW/REST+API#RESTAPI-VCSRoots

Code is a search-and-replace job on set_project_field.

### CODE REVIEW

**Comment by jperry** [comment]
@deadly11ama - could you create a test for it? I will merge shortly after.  Thanks!

**Comment by deadly11ama** [comment]
Before I go and do something stupid -- do the tests require a running TeamCity?  The existing tests run fine but when I add mine, I get Faraday::ConnectionRefused errors.

**Comment by jperry** [comment]
Yes, it does require an actual teamcity server up and running for new tests but afterwards it doesn't as it records the request and response.  Hopefully this isn't too much trouble to get running quickly.  I hope to add a vagrant file in the coming months to make this easier.  You could obviously mock out the call but I was trying to avoid that.  Thanks!

**Comment by deadly11ama** [comment]
I've been wrangling our TeamCity since 2009, I don't need no vagrant.

Also, here is a test (for my use-case), and it passes.

**Comment by jperry** [comment]
thx @deadly11ama .

**Comment by jperry** [comment]
Until I release just point to latest.

**Pull request merged**
