### PR TITLE
Teamcity8 support & bug fixes

### PR DESCRIPTION
**Pull request by emil-mi**
Series of patches that add methods for TC8 API and some small bug fix

### CODE REVIEW

**Comment by jperry** [comment]
@emil-mi - sorry it has taken me so long to get back to this as I switched jobs and have been busy there.  I'm still not happy about having another method called create_buildtype_ex as eventually this implementation would end up in create_buildtype.  So I see two options here, either we update create_buildtype to have these new changes and note this method is compatible with 8.1 and then have an old method for the old way.  Or add an api_version option when you create the client object and based on what version you specify it will load the correct one.  thoughts?

**Comment by jperry** [comment]
One other idea I had was add this new code to create_buildtype and allow the user to pass in a block or a proc that overrides the full body of the method for cases where they are still using < 8.1.

**Comment by jperry** [comment]
@emil-mi - thoughts on my comments above?  Would like get this PR complete.  Thanks!

**Comment by emil-mi** [comment]
@jperry - sorry. I was busy.
Now there is a new version of TeamCity (https://confluence.jetbrains.com/display/TCD9/REST+API#RESTAPI-RESTAPIVersions) and a new API version. It seems that there are no major changes but I see it as a sign that we are chasing an ever moving target so there is no one-size-fits-all solution.
Do you think that adjusting the available functions (and arguments) based  on the the targeted API version is ok?
(This would mean introducing an "version" configuration parameter, computing the correct http endpoint, and then injecting the appropriate methods signatures).

(Please keep in mind that I am not a seasoned Ruby programmer and if say something stupid (like "injecting methods") or not ruby-like, then I welcome your corrections)

**Pull request closed without merging**
